name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - name: build in docker
      run: sh -c 'cd $GITHUB_WORKSPACE && ./docker.sh'
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: ${{ github.workspace }}/mbp-16.1-linux-wifi-*-x86_64.pkg.tar.zst
